# Generated by Django 4.2.5 on 2023-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("ruc", models.CharField(max_length=100)),
                ("document_number", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("image_path", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                ("active", models.BooleanField()),
                ("person_type", models.CharField(max_length=20)),
                ("city_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
        ),
    ]
